### PR TITLE
Remove workflow + secret

### LINKED ISSUE #2: Deploy Landing page to cloudflare pages

### PR DESCRIPTION
**Pull request by LarsFlieger**
- Remove workflow + secrect from repo
- Auth Cloudflare Pages
- Setup "stable" branch to go on nextparty.io, www.nextparty.io!

What to check?
Check if booth domains work:

- https://nextparty.io/
- https://www.nextparty.io/

Cloudflare project:
https://dash.cloudflare.com/294fbcb165ae3b3d08d2f13263ddd94c/pages/view/truth-or-dare-landing

### CODE REVIEW

**Comment by coffemakingtoaster** [comment]
MR looks good. However check the issue and my question there before merging this (and therefore closing the issue).

**Review by coffeemakingtoaster — APPROVED** [review]
Looks good but don´t merge before validating that all steps of the issue are covered

**Comment by LarsFlieger** [comment]
> Looks good but don´t merge before validating that all steps of the issue are covered

I would also say: As rule we only allow merge by the author of the PR so we make sure the merge is correct and valid!

**Comment by coffeemakingtoaster** [comment]
> > Looks good but don´t merge before validating that all steps of the issue are covered
> 
> I would also say: As rule we only allow merge by the author of the PR so we make sure the merge is correct and valid!

Add this to discord. In the future we should add a contributing.md for topics like this.

**Comment by LarsFlieger** [comment]
> > > Looks good but don´t merge before validating that all steps of the issue are covered
> > 
> > 
> > I would also say: As rule we only allow merge by the author of the PR so we make sure the merge is correct and valid!
> 
> Add this to discord. In the future we should add a contributing.md for topics like this.

Great added task to projects board!

**Comment by coffeemakingtoaster** [comment]
With every aspect of the issue done this can be merged 👍

**Pull request merged**
